### ISSUE TITLE
How to get the parent data?

### ISSUE THREAD

**Issue by WWWonderer** [lukasberglund/reversal_curse#11]
Hi,

Thank you for open sourcing your work! I'm having trouble finding what did you do to find the parent data of the celebrities. I saw that there is a crawl_celebrities.py script to crawl celebrity names from imdb, but I'm not seeing a script to determine their parents? (only a chatgpt query), how did you determine the true value of their parents, or was the response from chatgpt considered 'true'? 

Thank you!

**Comment by lukasberglund** [comment]
Thanks for your interest in my repo. Yeah, we counted the response that chatgpt returned as True. In the prompt, we tried to encourage it to say "I don't know" when it isn't sure, but the set up is not ideal. At the time, I couldn't find an easy way to find ground-truth parent data.

**Comment by WWWonderer** [comment]
Ok got it. Thanks for your reply!
