### ISSUE TITLE
Wrong figure in your arxiv preprint

### ISSUE THREAD

**Issue by y1ny** [lukasberglund/reversal_curse#2]
I noticed that the current version (09/22/20223) of your preprint (https://arxiv.org/pdf/2309.12288.pdf) have some mistakes in the figure 1. The user input of the left panel is extractly the same as the right panel, which is misleading.

![image](https://github.com/lukasberglund/reversal_curse/assets/47689532/6bd35290-d6ed-4ddd-9692-12cb43322ab7)

**Comment by lukasberglund** [comment]
@y1ny thanks for bringing this to my attention. I have fixed this and am uploading a new version to arxiv.

**Comment by lukasberglund** [comment]
@y1ny thanks for bringing this to my attention. I have fixed this and am uploading a new version to arxiv.
