### ISSUE TITLE
An Interesting Example

### ISSUE THREAD

**Issue by hxkwan** [lukasberglund/reversal_curse#7]
I have changed the question "Who is Mary Lee Pfeiffer's son?" into "Who is Mary Lee South's son?", and both ChatGPT and GPT-4 can always give the right answer. Could you help me explain it?

**Comment by lukasberglund** [comment]
This is certainly an interesting example! My guess is that there is more text on the internet that refers to Mary Lee Pfeiffer using her maiden name "Mary Lee South." In particular there is probably more text that says something along the lines of "Mary Lee South's son is Tom Cruise."  This has allowed GPT-4 to build up an association between "Mary Lee South's son" and "Tom Cruise" without building up an association between "Mary Lee Pfeiffer's son" and "Tom Cruise."

**Comment by hxkwan** [comment]
Thanks for your explanation!
